### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by EvilCh33z** [mosemister/EntityDisguise#1]
Log:
[EntityDisguise_Error.txt](https://github.com/mosemister/EntityDisguise/files/644748/EntityDisguise_Error.txt)

**Comment by mosemister** [comment]
What version of sponge are you using? (Api wise)

**Comment by EvilCh33z** [comment]
Spongeforge 1.10.2-2171-5.1.0-BETA-1976.jar

**Comment by mosemister** [comment]
Entity disguise does not have a build for 5.1.0. the latest is 5.0.0. i am working on a 6.0.0 however i do not have plans for a 5.1.0 release yet

**Comment by EvilCh33z** [comment]
:( sadface

**Comment by mosemister** [comment]
That is not to say i will never make one. Just no plans yet
